apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: tf-text-clf-serve
  annotations:
    scenarios.ai.sap.com/description: "Tensorflow text classification"
    scenarios.ai.sap.com/name: "movie-review-clf"
    executables.ai.sap.com/description: "Tensorflow GPU Serving executable"
    executables.ai.sap.com/name: "serve-executable"
  labels:
    scenarios.ai.sap.com/id: "datarobot-servingscenario-20240515214049"
    ai.sap.com/version: "6"
spec:
  inputs:
    artifacts:
    - name: modelArtifact
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      labels: |
        ai.sap.com/resourcePlan: Starter
    spec: |
      predictor:
        imagePullSecrets:
          - name: datarobot-docsecret-20240515213332
        containers:
        - name: kfserving-container
          image: "docker.io/datarobotsapdemo/movie-review-clf-serve:6"
          ports:
            - containerPort: 9001
              protocol: TCP
          env:
            - name: STORAGE_URI
              value: "{{inputs.artifacts.modelArtifact}}"
